### ISSUE TITLE
Ошибка билда образа

### ISSUE THREAD

**Issue by Nelfimov** [atls/buildpacks#17]
### Описание бага

Билд образа валится если кэш yarn находится вне проекта.

### Воспроизведение

`.yarnrc.yml`

```yml
enableGlobalCache: true

globalFolder: ../.yarn/berry
``` 

### Ожидаемое поведение

Билд проходит успешно.

### Материалы

```
===> BUILDING
Timer: Builder started at 2024-07-29T15:41:30Z
Running build for buildpack tech.atlantislab.buildpacks.yarn-install@0.0.4
Looking up buildpack
Finding plan
Creating plan directory
Preparing paths
Running build command
Error: Command failed with exit code 1: yarn install --immutable --inline-builds
Internal Error: EACCES: permission denied, mkdir '/.yarn'
Error: EACCES: permission denied, mkdir '/.yarn'
    at makeError (/cnb/buildpacks/tech.atlantislab.buildpacks.yarn-install/0.0.4/dist/index.js:4068:11)
    at handlePromise (/cnb/buildpacks/tech.atlantislab.buildpacks.yarn-install/0.0.4/dist/index.js:3790:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async YarnInstallBuilder.build (/cnb/buildpacks/tech.atlantislab.buildpacks.yarn-install/0.0.4/dist/index.js:18:9)
    at async build (/cnb/buildpacks/tech.atlantislab.buildpacks.yarn-install/0.0.4/dist/index.js:137:20)
    at async run (/cnb/buildpacks/tech.atlantislab.buildpacks.yarn-install/0.0.4/dist/index.js:1131:17) {
  shortMessage: 'Command failed with exit code 1: yarn install --immutable --inline-builds',
  command: 'yarn install --immutable --inline-builds',
  escapedCommand: 'yarn install --immutable --inline-builds',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "Internal Error: EACCES: permission denied, mkdir '/.yarn'\n" +
    "Error: EACCES: permission denied, mkdir '/.yarn'",
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

https://github.com/rees46/shopify-app/actions/runs/10147437206/job/28057795189#step:9:365

### Данные окружения

tech.atlantislab.buildpacks.yarn-install         0.0.4
tech.atlantislab.buildpacks.yarn-cache           0.0.4
tech.atlantislab.buildpacks.yarn-workspace-start 0.0.4

**Comment by Nelfimov** [comment]
Решено в последней версии бандла
